name: Nightly Cron Run

on:
  schedule:
    - cron: '0 3 * * *' # 3 AM UTC (10 PM ET)
  workflow_dispatch: # manual trigger

jobs:
  run-crons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Run Crons
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          CRON_BASE_URL: ${{ secrets.CRON_BASE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: npm run cron
